# ---------------Add energy Tariffs-----------------
utility_meter:
  daily_energy:
    source: sensor.energy_meter_81_2
    name: Daily Energy
    cycle: daily
    tariffs:
      - peak
      - offpeak
      - night
  monthly_energy:
    source: sensor.energy_meter_81_2
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - peak
      - offpeak
      - night

#--------------------Add tarrif Based Cost Sensors--------------------     
sensor:
  - platform: template
    sensors:
     daily_esb_cost_peak:
        friendly_name: "Daily ESB cost peak"
        unit_of_measurement: '€'
        icon_template: mdi:currency-eur
        value_template: "{{ (states('sensor.daily_energy_peak') | float * 0.3661) | round(2) }}"
     daily_esb_cost_day:
        friendly_name: "Daily ESB cost day"
        unit_of_measurement: '€'
        icon_template: mdi:currency-eur
        value_template: "{{ (states('sensor.daily_energy_offpeak') | float  * 0.3494) | round(2) }}"
     daily_esb_cost_night:
        friendly_name: "Daily ESB cost night"
        unit_of_measurement: '€'
        icon_template: mdi:currency-eur
        value_template: "{{ (states('sensor.daily_energy_night') | float * 0.2497) | round(2) }}"
